Repository pantos-io/ethereum-contracts, pull requests merged in 2024-11, with the labels that each got.

#65 feat: add send tokens from safe script
  script/helpers/SafeAddresses.s.sol
  script/safes/SendTokens.s.sol
Labels: enhancement

#66 Create SECURITY.md
  SECURITY.md
Labels: documentation

#69 [PAN-2300] Publish ABI documentation
  .gas-snapshot
  .github/workflows/publish-docs.yaml
  .github/workflows/release.yaml
Labels: documentation

#73 fix: role name validation
  script/helpers/PantosBaseAddresses.s.sol
  script/helpers/SafeAddresses.s.sol
Labels: bug
